2020-07-31 13:21:02.897499 (MainThread): Running with dbt=0.17.2
2020-07-31 13:21:03.082201 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=False, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='default', models=None, partial_parse=True, port=8580, profile='user', profiles_dir='/usr/src/develop/.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2020-07-31 13:21:03.095356 (MainThread): Tracking: tracking
2020-07-31 13:21:03.095649 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30d362e48>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30d362d68>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30d3620f0>]}
2020-07-31 13:21:03.101777 (MainThread): Serving RPC server at 0.0.0.0:8580, pid=14
2020-07-31 13:21:03.105790 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'get-manifest', 'kill', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2020-07-31 13:21:03.106320 (MainThread): Send requests to http://localhost:8580/jsonrpc
2020-07-31 13:21:03.111996 (Thread-1): Parsing macros/core.sql
2020-07-31 13:21:03.117277 (Thread-1): Parsing macros/materializations/helpers.sql
2020-07-31 13:21:03.125704 (Thread-1): Parsing macros/materializations/common/merge.sql
2020-07-31 13:21:03.140230 (Thread-1): Parsing macros/materializations/table/table.sql
2020-07-31 13:21:03.147163 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2020-07-31 13:21:03.152040 (Thread-1): Parsing macros/materializations/view/view.sql
2020-07-31 13:21:03.158309 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2020-07-31 13:21:03.186983 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2020-07-31 13:21:03.203368 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-07-31 13:21:03.205134 (Thread-1): Parsing macros/materializations/seed/seed.sql
2020-07-31 13:21:03.225924 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2020-07-31 13:21:03.232344 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2020-07-31 13:21:03.234266 (Thread-1): Parsing macros/etc/query.sql
2020-07-31 13:21:03.235385 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2020-07-31 13:21:03.237558 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2020-07-31 13:21:03.238569 (Thread-1): Parsing macros/etc/datetime.sql
2020-07-31 13:21:03.247519 (Thread-1): Parsing macros/etc/get_custom_database.sql
2020-07-31 13:21:03.249240 (Thread-1): Parsing macros/etc/is_incremental.sql
2020-07-31 13:21:03.251117 (Thread-1): Parsing macros/adapters/common.sql
2020-07-31 13:21:03.302899 (Thread-1): Parsing macros/schema_tests/relationships.sql
2020-07-31 13:21:03.304264 (Thread-1): Parsing macros/schema_tests/unique.sql
2020-07-31 13:21:03.305432 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2020-07-31 13:21:03.307553 (Thread-1): Parsing macros/schema_tests/not_null.sql
2020-07-31 13:21:03.308791 (Thread-1): Parsing macros/adapters.sql
2020-07-31 13:21:03.342982 (Thread-1): Parsing macros/catalog.sql
2020-07-31 13:21:03.346129 (Thread-1): Parsing macros/materializations/incremental.sql
2020-07-31 13:21:03.359646 (Thread-1): Parsing macros/materializations/merge.sql
2020-07-31 13:21:03.362096 (Thread-1): Parsing macros/materializations/table.sql
2020-07-31 13:21:03.366396 (Thread-1): Parsing macros/materializations/view.sql
2020-07-31 13:21:03.552970 (Thread-1): Acquiring new snowflake connection "model.my_new_project.my_second_dbt_model".
2020-07-31 13:21:03.553124 (Thread-1): Opening a new connection, currently in state init
2020-07-31 13:21:03.587780 (Thread-1): Acquiring new snowflake connection "model.my_new_project.my_first_dbt_model".
2020-07-31 13:21:03.587924 (Thread-1): Opening a new connection, currently in state init
2020-07-31 13:21:03.858596 (Thread-2): handling status request
2020-07-31 13:21:03.859210 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c914fd0>]}
2020-07-31 13:21:03.864836 (Thread-2): sending response (<Response 9262 bytes [200 OK]>) to 10.0.35.54
2020-07-31 13:21:05.153208 (Thread-3): handling status request
2020-07-31 13:21:05.153726 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c8cba90>]}
2020-07-31 13:21:05.157926 (Thread-3): sending response (<Response 9262 bytes [200 OK]>) to 10.0.0.212
2020-07-31 13:21:36.838433 (Thread-4): handling status request
2020-07-31 13:21:36.840277 (Thread-4): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c833c88>]}
2020-07-31 13:21:36.844117 (Thread-4): sending response (<Response 9262 bytes [200 OK]>) to 10.0.43.94
2020-07-31 13:21:36.862483 (Thread-5): handling status request
2020-07-31 13:21:36.862818 (Thread-5): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c850748>]}
2020-07-31 13:21:36.866529 (Thread-5): sending response (<Response 9262 bytes [200 OK]>) to 10.0.24.186
2020-07-31 13:21:37.032939 (Thread-6): handling cli_args request
2020-07-31 13:21:37.033368 (Thread-6): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9db320>]}
2020-07-31 13:21:37.045554 (Thread-6): Connection 'model.my_new_project.my_first_dbt_model' was properly closed.
2020-07-31 13:21:38.008407 (Thread-6): sending response (<Response 136 bytes [200 OK]>) to 10.0.34.28
2020-07-31 13:21:38.065269 (MainThread): Partial parsing not enabled
2020-07-31 13:21:38.067213 (MainThread): Parsing macros/core.sql
2020-07-31 13:21:38.071662 (MainThread): Parsing macros/materializations/helpers.sql
2020-07-31 13:21:38.079700 (MainThread): Parsing macros/materializations/common/merge.sql
2020-07-31 13:21:38.093701 (MainThread): Parsing macros/materializations/table/table.sql
2020-07-31 13:21:38.100420 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2020-07-31 13:21:38.105466 (MainThread): Parsing macros/materializations/view/view.sql
2020-07-31 13:21:38.111976 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2020-07-31 13:21:38.140053 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2020-07-31 13:21:38.156416 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-07-31 13:21:38.158210 (MainThread): Parsing macros/materializations/seed/seed.sql
2020-07-31 13:21:38.178902 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2020-07-31 13:21:38.185120 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2020-07-31 13:21:38.187089 (MainThread): Parsing macros/etc/query.sql
2020-07-31 13:21:38.188219 (MainThread): Parsing macros/etc/get_custom_schema.sql
2020-07-31 13:21:38.190293 (MainThread): Parsing macros/etc/get_custom_alias.sql
2020-07-31 13:21:38.191330 (MainThread): Parsing macros/etc/datetime.sql
2020-07-31 13:21:38.200310 (MainThread): Parsing macros/etc/get_custom_database.sql
2020-07-31 13:21:38.202027 (MainThread): Parsing macros/etc/is_incremental.sql
2020-07-31 13:21:38.203809 (MainThread): Parsing macros/adapters/common.sql
2020-07-31 13:21:38.252775 (MainThread): Parsing macros/schema_tests/relationships.sql
2020-07-31 13:21:38.254011 (MainThread): Parsing macros/schema_tests/unique.sql
2020-07-31 13:21:38.255197 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2020-07-31 13:21:38.257282 (MainThread): Parsing macros/schema_tests/not_null.sql
2020-07-31 13:21:38.258508 (MainThread): Parsing macros/adapters.sql
2020-07-31 13:21:38.281185 (MainThread): Parsing macros/catalog.sql
2020-07-31 13:21:38.283156 (MainThread): Parsing macros/materializations/incremental.sql
2020-07-31 13:21:38.294651 (Thread-7): handling poll request
2020-07-31 13:21:38.292176 (MainThread): Parsing macros/materializations/merge.sql
2020-07-31 13:21:38.295699 (Thread-7): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c899cf8>]}
2020-07-31 13:21:38.301185 (Thread-7): sending response (<Response 7963 bytes [200 OK]>) to 10.0.39.221
2020-07-31 13:21:38.294189 (MainThread): Parsing macros/materializations/table.sql
2020-07-31 13:21:38.297860 (MainThread): Parsing macros/materializations/view.sql
2020-07-31 13:21:38.303226 (MainThread): Partial parsing not enabled
2020-07-31 13:21:38.347714 (MainThread): Acquiring new snowflake connection "model.my_new_project.my_second_dbt_model".
2020-07-31 13:21:38.347808 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:21:38.382360 (MainThread): Acquiring new snowflake connection "model.my_new_project.my_first_dbt_model".
2020-07-31 13:21:38.382479 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:21:38.660433 (MainThread): Found 2 models, 4 tests, 0 snapshots, 0 analyses, 136 macros, 0 operations, 0 seed files, 0 sources
2020-07-31 13:21:38.661154 (MainThread): 
2020-07-31 13:21:38.661418 (MainThread): Acquiring new snowflake connection "master".
2020-07-31 13:21:38.661485 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:21:38.664565 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "list_RAW".
2020-07-31 13:21:38.664658 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2020-07-31 13:21:38.677444 (ThreadPoolExecutor-0_0): Using snowflake connection "list_RAW".
2020-07-31 13:21:38.677526 (ThreadPoolExecutor-0_0): On list_RAW: /* {"app": "dbt", "dbt_version": "0.17.2", "profile_name": "user", "target_name": "default", "connection_name": "list_RAW"} */

    show terse schemas in database RAW
    limit 10000
2020-07-31 13:21:39.052961 (ThreadPoolExecutor-0_0): unclosed file <_io.BufferedReader name='/usr/local/lib/python3.6/dist-packages/certifi/cacert.pem'>
2020-07-31 13:21:39.489602 (Thread-8): handling poll request
2020-07-31 13:21:39.490094 (Thread-8): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c907dd8>]}
2020-07-31 13:21:39.492499 (Thread-8): sending response (<Response 4751 bytes [200 OK]>) to 10.0.35.54
2020-07-31 13:21:39.707571 (ThreadPoolExecutor-0_0): SQL status: SUCCESS 8 in 1.03 seconds
2020-07-31 13:21:39.711147 (ThreadPoolExecutor-0_0): On list_RAW: Close
2020-07-31 13:21:40.014900 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:21:40.015009 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state closed
2020-07-31 13:21:40.015192 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:21:40.015244 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state closed
2020-07-31 13:21:40.015378 (ThreadPoolExecutor-0_0): Creating schema "RAW.dbt_kcoapman"
2020-07-31 13:21:40.021092 (ThreadPoolExecutor-0_0): Using snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:21:40.021187 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: BEGIN
2020-07-31 13:21:40.661663 (Thread-9): handling poll request
2020-07-31 13:21:40.663622 (Thread-9): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c90b4a8>]}
2020-07-31 13:21:40.665423 (Thread-9): sending response (<Response 2896 bytes [200 OK]>) to 10.0.16.17
2020-07-31 13:21:40.799181 (ThreadPoolExecutor-0_0): SQL status: SUCCESS 1 in 0.78 seconds
2020-07-31 13:21:40.799317 (ThreadPoolExecutor-0_0): Using snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:21:40.799369 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: /* {"app": "dbt", "dbt_version": "0.17.2", "profile_name": "user", "target_name": "default", "connection_name": "create_RAW_dbt_kcoapman"} */
create schema if not exists RAW.dbt_kcoapman
2020-07-31 13:21:40.998160 (ThreadPoolExecutor-0_0): Snowflake query id: 0195ef61-03a3-fbb0-0007-9783002352c2
2020-07-31 13:21:40.998268 (ThreadPoolExecutor-0_0): Snowflake error: 003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'RAW'
2020-07-31 13:21:40.998377 (ThreadPoolExecutor-0_0): Error running SQL: macro create_schema
2020-07-31 13:21:40.998424 (ThreadPoolExecutor-0_0): Rolling back transaction.
2020-07-31 13:21:40.998485 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: ROLLBACK
2020-07-31 13:21:41.296634 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: Close
2020-07-31 13:21:41.558535 (MainThread): Connection 'master' was properly closed.
2020-07-31 13:21:41.558655 (MainThread): Connection 'create_RAW_dbt_kcoapman' was properly closed.
2020-07-31 13:21:41.558713 (MainThread): dbt runtime exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 158, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 77, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/cursor.py", line 597, in execute
    errvalue)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.ProgrammingError: 003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'RAW'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/task_handler.py", line 95, in task_exec
    result = self.task.handle_request()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/cli.py", line 110, in handle_request
    return self.real_task.handle_request()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/project_commands.py", line 54, in handle_request
    return self.run()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 410, in run
    result = self.execute_with_hooks(selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 370, in execute_with_hooks
    self.before_run(adapter, selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/run.py", line 203, in before_run
    self.create_schemas(adapter, selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 514, in create_schemas
    create_future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/utils.py", line 526, in connected
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 476, in create_schema
    adapter.create_schema(relation)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/impl.py", line 183, in create_schema
    self.execute_macro(CREATE_SCHEMA_MACRO_NAME, kwargs=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 976, in execute_macro
    result = macro_function(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 19, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 101, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 28, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 228, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 122, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 304, in add_query
    abridge_sql_log=abridge_sql_log
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 85, in add_query
    return connection, cursor
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 175, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  003001 (42501): SQL access control error:
  Insufficient privileges to operate on database 'RAW'
2020-07-31 13:21:41.882676 (Thread-10): handling poll request
2020-07-31 13:21:41.883218 (Thread-10): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c904a58>]}
2020-07-31 13:21:41.884267 (Thread-10): sending response (<Response 24945 bytes [200 OK]>) to 10.0.12.102
2020-07-31 13:21:42.113432 (Thread-11): handling status request
2020-07-31 13:21:42.113903 (Thread-11): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c974080>]}
2020-07-31 13:21:42.117784 (Thread-11): sending response (<Response 9262 bytes [200 OK]>) to 10.0.39.221
2020-07-31 13:23:29.804652 (Thread-12): handling status request
2020-07-31 13:23:29.806486 (Thread-12): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9b3438>]}
2020-07-31 13:23:29.810365 (Thread-12): sending response (<Response 9262 bytes [200 OK]>) to 10.0.26.29
2020-07-31 13:23:29.998611 (Thread-13): handling run_sql request
2020-07-31 13:23:29.999120 (Thread-13): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9813c8>]}
2020-07-31 13:23:30.995184 (Thread-13): sending response (<Response 136 bytes [200 OK]>) to 10.0.34.28
2020-07-31 13:23:31.015634 (MainThread): Acquiring new snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:31.016025 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:23:31.045105 (MainThread): Found 2 models, 4 tests, 0 snapshots, 0 analyses, 136 macros, 0 operations, 0 seed files, 0 sources
2020-07-31 13:23:31.045756 (Thread-1): Acquiring new snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:31.045856 (Thread-1): Opening a new connection, currently in state init
2020-07-31 13:23:31.045932 (Thread-1): Compiling rpc.my_new_project.request
2020-07-31 13:23:31.058045 (Thread-1): finished collecting timing info
2020-07-31 13:23:31.058543 (Thread-1): Using snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:31.058610 (Thread-1): On rpc.my_new_project.request: select *
from raw.jaffle_shop.orders;
2020-07-31 13:23:31.242106 (Thread-14): handling poll request
2020-07-31 13:23:31.242607 (Thread-14): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9813c8>]}
2020-07-31 13:23:31.244932 (Thread-14): sending response (<Response 3154 bytes [200 OK]>) to 10.0.7.55
2020-07-31 13:23:31.481968 (Thread-1): unclosed file <_io.BufferedReader name='/usr/local/lib/python3.6/dist-packages/certifi/cacert.pem'>
2020-07-31 13:23:32.388629 (Thread-15): handling poll request
2020-07-31 13:23:32.389136 (Thread-15): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c90bb00>]}
2020-07-31 13:23:32.390104 (Thread-15): sending response (<Response 393 bytes [200 OK]>) to 10.0.31.94
2020-07-31 13:23:32.449741 (Thread-1): SQL status: SUCCESS 99 in 1.39 seconds
2020-07-31 13:23:32.449940 (Thread-1): Using snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:32.450000 (Thread-1): On rpc.my_new_project.request: limit 100
2020-07-31 13:23:32.581895 (Thread-1): Snowflake query id: 0195ef63-03fc-b2c5-0007-9783002334a6
2020-07-31 13:23:32.582016 (Thread-1): Snowflake error: 001003 (42000): SQL compilation error:
syntax error line 1 at position 0 unexpected 'limit'.
2020-07-31 13:23:32.582142 (Thread-1): finished collecting timing info
2020-07-31 13:23:32.582608 (Thread-1): On rpc.my_new_project.request: Close
2020-07-31 13:23:32.793500 (Thread-1): Got an exception: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 0 unexpected 'limit'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 158, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 77, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/cursor.py", line 597, in execute
    errvalue)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 0 unexpected 'limit'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 228, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 171, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 273, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 86, in execute
    compiled_node.injected_sql, fetch=True
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 228, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 122, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 304, in add_query
    abridge_sql_log=abridge_sql_log
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 85, in add_query
    return connection, cursor
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 175, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 0 unexpected 'limit'.
2020-07-31 13:23:32.795177 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 0 unexpected 'limit'.", 'raw_sql': 'select *\nfrom raw.jaffle_shop.orders;\nlimit 100', 'compiled_sql': 'select *\nfrom raw.jaffle_shop.orders;\nlimit 100', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/sql_commands.py", line 165, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.6/dist-packages/dbt/node_runners.py", line 244, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/node_runners.py", line 53, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 0 unexpected 'limit'.", 'raw_sql': 'select *\nfrom raw.jaffle_shop.orders;\nlimit 100', 'compiled_sql': 'select *\nfrom raw.jaffle_shop.orders;\nlimit 100', 'tags': None}, None)
2020-07-31 13:23:33.575576 (Thread-16): handling poll request
2020-07-31 13:23:33.577900 (Thread-16): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c980a58>]}
2020-07-31 13:23:33.578769 (Thread-16): sending response (<Response 9760 bytes [200 OK]>) to 10.0.35.54
2020-07-31 13:23:50.135306 (Thread-17): handling status request
2020-07-31 13:23:50.137341 (Thread-17): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c980908>]}
2020-07-31 13:23:50.141252 (Thread-17): sending response (<Response 9262 bytes [200 OK]>) to 10.0.31.94
2020-07-31 13:23:50.317355 (Thread-18): handling compile_sql request
2020-07-31 13:23:50.317774 (Thread-18): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9b3ef0>]}
2020-07-31 13:23:51.289978 (Thread-18): sending response (<Response 136 bytes [200 OK]>) to 10.0.31.94
2020-07-31 13:23:51.310797 (MainThread): Acquiring new snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:51.311236 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:23:51.338216 (MainThread): Found 2 models, 4 tests, 0 snapshots, 0 analyses, 136 macros, 0 operations, 0 seed files, 0 sources
2020-07-31 13:23:51.338950 (Thread-1): Acquiring new snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:51.339071 (Thread-1): Opening a new connection, currently in state init
2020-07-31 13:23:51.339151 (Thread-1): Compiling rpc.my_new_project.request
2020-07-31 13:23:51.351758 (Thread-1): finished collecting timing info
2020-07-31 13:23:51.352036 (Thread-1): finished collecting timing info
2020-07-31 13:23:51.540514 (Thread-19): handling poll request
2020-07-31 13:23:51.541020 (Thread-19): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9b3ef0>]}
2020-07-31 13:23:51.546655 (Thread-19): sending response (<Response 4425 bytes [200 OK]>) to 10.0.35.54
2020-07-31 13:23:56.192307 (Thread-20): handling status request
2020-07-31 13:23:56.194687 (Thread-20): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c914128>]}
2020-07-31 13:23:56.198615 (Thread-20): sending response (<Response 9262 bytes [200 OK]>) to 10.0.0.212
2020-07-31 13:23:56.391448 (Thread-21): handling run_sql request
2020-07-31 13:23:56.391812 (Thread-21): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c918710>]}
2020-07-31 13:23:57.363643 (Thread-21): sending response (<Response 136 bytes [200 OK]>) to 10.0.39.221
2020-07-31 13:23:57.384215 (MainThread): Acquiring new snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:57.384601 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:23:57.411226 (MainThread): Found 2 models, 4 tests, 0 snapshots, 0 analyses, 136 macros, 0 operations, 0 seed files, 0 sources
2020-07-31 13:23:57.411879 (Thread-1): Acquiring new snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:57.411974 (Thread-1): Opening a new connection, currently in state init
2020-07-31 13:23:57.412051 (Thread-1): Compiling rpc.my_new_project.request
2020-07-31 13:23:57.424380 (Thread-1): finished collecting timing info
2020-07-31 13:23:57.424854 (Thread-1): Using snowflake connection "rpc.my_new_project.request".
2020-07-31 13:23:57.424922 (Thread-1): On rpc.my_new_project.request: select *
from raw.jaffle_shop.orders
2020-07-31 13:23:57.519521 (Thread-22): handling poll request
2020-07-31 13:23:57.519956 (Thread-22): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c91f780>]}
2020-07-31 13:23:57.522133 (Thread-22): sending response (<Response 3152 bytes [200 OK]>) to 10.0.16.100
2020-07-31 13:23:57.784534 (Thread-1): unclosed file <_io.BufferedReader name='/usr/local/lib/python3.6/dist-packages/certifi/cacert.pem'>
2020-07-31 13:23:58.604951 (Thread-1): SQL status: SUCCESS 99 in 1.18 seconds
2020-07-31 13:23:58.610541 (Thread-1): finished collecting timing info
2020-07-31 13:23:58.611060 (Thread-1): On rpc.my_new_project.request: Close
2020-07-31 13:23:58.707854 (Thread-23): handling poll request
2020-07-31 13:23:58.708315 (Thread-23): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9805f8>]}
2020-07-31 13:23:58.709565 (Thread-23): sending response (<Response 1338 bytes [200 OK]>) to 10.0.12.102
2020-07-31 13:23:59.893104 (Thread-24): handling poll request
2020-07-31 13:23:59.895067 (Thread-24): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c918710>]}
2020-07-31 13:23:59.899979 (Thread-24): sending response (<Response 9478 bytes [200 OK]>) to 10.0.43.61
2020-07-31 13:25:42.187627 (Thread-25): handling status request
2020-07-31 13:25:42.189916 (Thread-25): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c91ffd0>]}
2020-07-31 13:25:42.193796 (Thread-25): sending response (<Response 9262 bytes [200 OK]>) to 10.0.16.17
2020-07-31 13:25:42.221504 (Thread-26): handling status request
2020-07-31 13:25:42.221940 (Thread-26): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c8b39b0>]}
2020-07-31 13:25:42.225651 (Thread-26): sending response (<Response 9262 bytes [200 OK]>) to 10.0.35.54
2020-07-31 13:25:42.505844 (Thread-27): handling cli_args request
2020-07-31 13:25:42.506350 (Thread-27): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9e4f28>]}
2020-07-31 13:25:43.558455 (Thread-27): sending response (<Response 136 bytes [200 OK]>) to 10.0.34.28
2020-07-31 13:25:43.615836 (MainThread): Partial parsing not enabled
2020-07-31 13:25:43.617736 (MainThread): Parsing macros/core.sql
2020-07-31 13:25:43.622217 (MainThread): Parsing macros/materializations/helpers.sql
2020-07-31 13:25:43.630404 (MainThread): Parsing macros/materializations/common/merge.sql
2020-07-31 13:25:43.644408 (MainThread): Parsing macros/materializations/table/table.sql
2020-07-31 13:25:43.652735 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2020-07-31 13:25:43.657675 (MainThread): Parsing macros/materializations/view/view.sql
2020-07-31 13:25:43.664665 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2020-07-31 13:25:43.693937 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2020-07-31 13:25:43.710405 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-07-31 13:25:43.712223 (MainThread): Parsing macros/materializations/seed/seed.sql
2020-07-31 13:25:43.733013 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2020-07-31 13:25:43.739454 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2020-07-31 13:25:43.741348 (MainThread): Parsing macros/etc/query.sql
2020-07-31 13:25:43.742465 (MainThread): Parsing macros/etc/get_custom_schema.sql
2020-07-31 13:25:43.744614 (MainThread): Parsing macros/etc/get_custom_alias.sql
2020-07-31 13:25:43.745625 (MainThread): Parsing macros/etc/datetime.sql
2020-07-31 13:25:43.754596 (MainThread): Parsing macros/etc/get_custom_database.sql
2020-07-31 13:25:43.756341 (MainThread): Parsing macros/etc/is_incremental.sql
2020-07-31 13:25:43.758070 (MainThread): Parsing macros/adapters/common.sql
2020-07-31 13:25:43.807127 (MainThread): Parsing macros/schema_tests/relationships.sql
2020-07-31 13:25:43.808386 (MainThread): Parsing macros/schema_tests/unique.sql
2020-07-31 13:25:43.809539 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2020-07-31 13:25:43.811604 (MainThread): Parsing macros/schema_tests/not_null.sql
2020-07-31 13:25:43.812833 (MainThread): Parsing macros/adapters.sql
2020-07-31 13:25:43.834694 (MainThread): Parsing macros/catalog.sql
2020-07-31 13:25:43.836681 (MainThread): Parsing macros/materializations/incremental.sql
2020-07-31 13:25:43.846712 (Thread-28): handling poll request
2020-07-31 13:25:43.847308 (Thread-28): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c9e4f28>]}
2020-07-31 13:25:43.851163 (Thread-28): sending response (<Response 7718 bytes [200 OK]>) to 10.0.35.54
2020-07-31 13:25:43.845671 (MainThread): Parsing macros/materializations/merge.sql
2020-07-31 13:25:43.847807 (MainThread): Parsing macros/materializations/table.sql
2020-07-31 13:25:43.851376 (MainThread): Parsing macros/materializations/view.sql
2020-07-31 13:25:43.856963 (MainThread): Partial parsing not enabled
2020-07-31 13:25:43.902923 (MainThread): Acquiring new snowflake connection "model.my_new_project.my_second_dbt_model".
2020-07-31 13:25:43.903021 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:25:43.936789 (MainThread): Acquiring new snowflake connection "model.my_new_project.my_first_dbt_model".
2020-07-31 13:25:43.936880 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:25:44.226896 (MainThread): Found 2 models, 4 tests, 0 snapshots, 0 analyses, 136 macros, 0 operations, 0 seed files, 0 sources
2020-07-31 13:25:44.227721 (MainThread): 
2020-07-31 13:25:44.228043 (MainThread): Acquiring new snowflake connection "master".
2020-07-31 13:25:44.228116 (MainThread): Opening a new connection, currently in state init
2020-07-31 13:25:44.231294 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "list_RAW".
2020-07-31 13:25:44.231381 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2020-07-31 13:25:44.244281 (ThreadPoolExecutor-0_0): Using snowflake connection "list_RAW".
2020-07-31 13:25:44.244364 (ThreadPoolExecutor-0_0): On list_RAW: /* {"app": "dbt", "dbt_version": "0.17.2", "profile_name": "user", "target_name": "default", "connection_name": "list_RAW"} */

    show terse schemas in database RAW
    limit 10000
2020-07-31 13:25:44.667511 (ThreadPoolExecutor-0_0): unclosed file <_io.BufferedReader name='/usr/local/lib/python3.6/dist-packages/certifi/cacert.pem'>
2020-07-31 13:25:45.048490 (Thread-29): handling poll request
2020-07-31 13:25:45.048993 (Thread-29): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c5900b8>]}
2020-07-31 13:25:45.051477 (Thread-29): sending response (<Response 5040 bytes [200 OK]>) to 10.0.35.54
2020-07-31 13:25:46.204827 (Thread-30): handling poll request
2020-07-31 13:25:46.206894 (Thread-30): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c60b1d0>]}
2020-07-31 13:25:46.371642 (Thread-30): sending response (<Response 286 bytes [200 OK]>) to 10.0.16.100
2020-07-31 13:25:46.479296 (ThreadPoolExecutor-0_0): SQL status: SUCCESS 8 in 2.23 seconds
2020-07-31 13:25:46.482886 (ThreadPoolExecutor-0_0): On list_RAW: Close
2020-07-31 13:25:47.121706 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:25:47.121828 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state closed
2020-07-31 13:25:47.122005 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:25:47.122058 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state closed
2020-07-31 13:25:47.122190 (ThreadPoolExecutor-0_0): Creating schema "RAW.dbt_kcoapman"
2020-07-31 13:25:47.127514 (ThreadPoolExecutor-0_0): Using snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:25:47.127600 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: BEGIN
2020-07-31 13:25:47.566316 (Thread-31): handling poll request
2020-07-31 13:25:47.566795 (Thread-31): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c60b1d0>]}
2020-07-31 13:25:47.568660 (Thread-31): sending response (<Response 2905 bytes [200 OK]>) to 10.0.43.61
2020-07-31 13:25:48.041025 (ThreadPoolExecutor-0_0): SQL status: SUCCESS 1 in 0.91 seconds
2020-07-31 13:25:48.041174 (ThreadPoolExecutor-0_0): Using snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:25:48.041231 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: /* {"app": "dbt", "dbt_version": "0.17.2", "profile_name": "user", "target_name": "default", "connection_name": "create_RAW_dbt_kcoapman"} */
create schema if not exists RAW.dbt_kcoapman
2020-07-31 13:25:48.695413 (ThreadPoolExecutor-0_0): Snowflake query id: 0195ef65-038c-64dc-0007-9783002334b2
2020-07-31 13:25:48.695531 (ThreadPoolExecutor-0_0): Snowflake error: 003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'RAW'
2020-07-31 13:25:48.695643 (ThreadPoolExecutor-0_0): Error running SQL: macro create_schema
2020-07-31 13:25:48.695690 (ThreadPoolExecutor-0_0): Rolling back transaction.
2020-07-31 13:25:48.695755 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: ROLLBACK
2020-07-31 13:25:48.758686 (Thread-32): handling poll request
2020-07-31 13:25:48.759242 (Thread-32): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c0dcbe0>]}
2020-07-31 13:25:48.760960 (Thread-32): sending response (<Response 2846 bytes [200 OK]>) to 10.0.2.188
2020-07-31 13:25:49.209468 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: Close
2020-07-31 13:25:49.456388 (MainThread): Connection 'master' was properly closed.
2020-07-31 13:25:49.456560 (MainThread): Connection 'create_RAW_dbt_kcoapman' was properly closed.
2020-07-31 13:25:49.456658 (MainThread): dbt runtime exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 158, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 77, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/cursor.py", line 597, in execute
    errvalue)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.ProgrammingError: 003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'RAW'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/task_handler.py", line 95, in task_exec
    result = self.task.handle_request()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/cli.py", line 110, in handle_request
    return self.real_task.handle_request()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/project_commands.py", line 54, in handle_request
    return self.run()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 410, in run
    result = self.execute_with_hooks(selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 370, in execute_with_hooks
    self.before_run(adapter, selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/run.py", line 203, in before_run
    self.create_schemas(adapter, selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 514, in create_schemas
    create_future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/utils.py", line 526, in connected
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 476, in create_schema
    adapter.create_schema(relation)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/impl.py", line 183, in create_schema
    self.execute_macro(CREATE_SCHEMA_MACRO_NAME, kwargs=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 976, in execute_macro
    result = macro_function(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 19, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 101, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 28, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 228, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 122, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 304, in add_query
    abridge_sql_log=abridge_sql_log
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 85, in add_query
    return connection, cursor
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 175, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  003001 (42501): SQL access control error:
  Insufficient privileges to operate on database 'RAW'
2020-07-31 13:25:49.914632 (Thread-33): handling poll request
2020-07-31 13:25:49.915168 (Thread-33): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c598828>]}
2020-07-31 13:25:49.916265 (Thread-33): sending response (<Response 25009 bytes [200 OK]>) to 10.0.16.100
2020-07-31 13:25:50.108301 (Thread-34): handling status request
2020-07-31 13:25:50.108762 (Thread-34): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c0e0ac8>]}
2020-07-31 13:25:50.112596 (Thread-34): sending response (<Response 9262 bytes [200 OK]>) to 10.0.43.94
2020-07-31 13:35:30.957061 (Thread-35): handling status request
2020-07-31 13:35:30.959013 (Thread-35): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c0f3940>]}
2020-07-31 13:35:30.963253 (Thread-35): sending response (<Response 9262 bytes [200 OK]>) to 10.0.34.28
2020-07-31 13:35:30.991495 (Thread-36): handling ps request
2020-07-31 13:35:30.991856 (Thread-36): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'b07bda4d-b4b0-4e3e-af6e-96a8d521698c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd30c0f5588>]}
2020-07-31 13:35:30.995143 (Thread-36): sending response (<Response 2426 bytes [200 OK]>) to 10.0.16.100
2020-07-31 13:35:39.773250 (MainThread): Running with dbt=0.17.0
2020-07-31 13:35:39.942092 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=False, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='default', models=None, partial_parse=True, port=8580, profile='user', profiles_dir='/usr/src/develop/.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2020-07-31 13:35:39.963188 (MainThread): Tracking: tracking
2020-07-31 13:35:39.963354 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf5438588>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf54386d8>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf5449278>]}
2020-07-31 13:35:39.963659 (MainThread): Serving RPC server at 0.0.0.0:8580, pid=13
2020-07-31 13:35:39.964068 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'get-manifest', 'kill', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2020-07-31 13:35:39.964391 (MainThread): Send requests to http://localhost:8580/jsonrpc
2020-07-31 13:35:39.968490 (Thread-1): Parsing macros/core.sql
2020-07-31 13:35:39.972969 (Thread-1): Parsing macros/materializations/helpers.sql
2020-07-31 13:35:39.981091 (Thread-1): Parsing macros/materializations/common/merge.sql
2020-07-31 13:35:39.995783 (Thread-1): Parsing macros/materializations/table/table.sql
2020-07-31 13:35:40.002788 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2020-07-31 13:35:40.007887 (Thread-1): Parsing macros/materializations/view/view.sql
2020-07-31 13:35:40.014346 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2020-07-31 13:35:40.043347 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2020-07-31 13:35:40.060440 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-07-31 13:35:40.062273 (Thread-1): Parsing macros/materializations/seed/seed.sql
2020-07-31 13:35:40.083736 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2020-07-31 13:35:40.090236 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2020-07-31 13:35:40.092205 (Thread-1): Parsing macros/etc/query.sql
2020-07-31 13:35:40.093339 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2020-07-31 13:35:40.095527 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2020-07-31 13:35:40.096574 (Thread-1): Parsing macros/etc/datetime.sql
2020-07-31 13:35:40.105921 (Thread-1): Parsing macros/etc/get_custom_database.sql
2020-07-31 13:35:40.107752 (Thread-1): Parsing macros/etc/is_incremental.sql
2020-07-31 13:35:40.109503 (Thread-1): Parsing macros/adapters/common.sql
2020-07-31 13:35:40.161755 (Thread-1): Parsing macros/schema_tests/relationships.sql
2020-07-31 13:35:40.163003 (Thread-1): Parsing macros/schema_tests/unique.sql
2020-07-31 13:35:40.164204 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2020-07-31 13:35:40.166280 (Thread-1): Parsing macros/schema_tests/not_null.sql
2020-07-31 13:35:40.167578 (Thread-1): Parsing macros/adapters.sql
2020-07-31 13:35:40.190772 (Thread-1): Parsing macros/catalog.sql
2020-07-31 13:35:40.192819 (Thread-1): Parsing macros/materializations/incremental.sql
2020-07-31 13:35:40.202140 (Thread-1): Parsing macros/materializations/merge.sql
2020-07-31 13:35:40.204250 (Thread-1): Parsing macros/materializations/table.sql
2020-07-31 13:35:40.207997 (Thread-1): Parsing macros/materializations/view.sql
2020-07-31 13:35:40.360672 (Thread-1): Acquiring new snowflake connection "model.my_new_project.my_second_dbt_model".
2020-07-31 13:35:40.360818 (Thread-1): Opening a new connection, currently in state init
2020-07-31 13:35:40.397284 (Thread-1): Acquiring new snowflake connection "model.my_new_project.my_first_dbt_model".
2020-07-31 13:35:40.397400 (Thread-1): Opening a new connection, currently in state init
2020-07-31 13:35:40.722489 (Thread-2): handling status request
2020-07-31 13:35:40.722885 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf4993e10>]}
2020-07-31 13:35:40.727773 (Thread-2): sending response (<Response 9262 bytes [200 OK]>) to 10.0.31.94
2020-07-31 13:35:40.913089 (Thread-3): handling status request
2020-07-31 13:35:40.913479 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf4ad9a90>]}
2020-07-31 13:35:40.917370 (Thread-3): sending response (<Response 9262 bytes [200 OK]>) to 10.0.24.186
2020-07-31 13:35:46.904611 (Thread-4): * Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - my_new_project

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0
2020-07-31 13:35:46.917679 (Thread-4): For key my_new_project, hash mismatch (FileHash(name='sha256', checksum='8b5e2651d3450c4b7e1c2a316e64987791297c739bc4a2715f6d4ad21852e926') -> FileHash(name='sha256', checksum='dcd4aa9ba70ffcc74d71c289865f18d2c90c259bd0d734efbba4ea9400d7e481')), cache invalidated
2020-07-31 13:35:46.964081 (Thread-4): Acquiring new snowflake connection "model.my_new_project.my_second_dbt_model".
2020-07-31 13:35:46.964227 (Thread-4): Opening a new connection, currently in state init
2020-07-31 13:35:46.974863 (Thread-4): Acquiring new snowflake connection "model.my_new_project.my_first_dbt_model".
2020-07-31 13:35:46.974979 (Thread-4): Opening a new connection, currently in state init
2020-07-31 13:35:47.060415 (Thread-5): handling status request
2020-07-31 13:35:47.065116 (Thread-5): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf4626550>]}
2020-07-31 13:35:47.065912 (Thread-5): sending response (<Response 183 bytes [200 OK]>) to 10.0.7.55
2020-07-31 13:35:48.255693 (Thread-6): handling status request
2020-07-31 13:35:48.256277 (Thread-6): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf46a6128>]}
2020-07-31 13:35:48.257727 (Thread-6): sending response (<Response 2486 bytes [200 OK]>) to 10.0.7.111
2020-07-31 13:35:49.489996 (Thread-7): handling status request
2020-07-31 13:35:49.490487 (Thread-7): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf49f52e8>]}
2020-07-31 13:35:49.491872 (Thread-7): sending response (<Response 2486 bytes [200 OK]>) to 10.0.31.94
2020-07-31 13:35:49.502890 (Thread-8): handling status request
2020-07-31 13:35:49.503273 (Thread-8): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf470e5c0>]}
2020-07-31 13:35:49.504519 (Thread-8): sending response (<Response 2486 bytes [200 OK]>) to 10.0.7.111
2020-07-31 13:35:49.697909 (Thread-9): handling cli_args request
2020-07-31 13:35:49.698356 (Thread-9): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf46cb7f0>]}
2020-07-31 13:35:49.709261 (Thread-9): Connection 'model.my_new_project.my_first_dbt_model' was properly closed.
2020-07-31 13:35:49.715097 (Thread-9): sending response (<Response 136 bytes [200 OK]>) to 10.0.43.94
2020-07-31 13:35:49.721389 (Thread-9): Partial parsing not enabled
2020-07-31 13:35:49.764154 (Thread-9): Acquiring new snowflake connection "model.my_new_project.my_second_dbt_model".
2020-07-31 13:35:49.764305 (Thread-9): Opening a new connection, currently in state init
2020-07-31 13:35:49.775711 (Thread-9): Acquiring new snowflake connection "model.my_new_project.my_first_dbt_model".
2020-07-31 13:35:49.775818 (Thread-9): Opening a new connection, currently in state init
2020-07-31 13:35:49.899084 (Thread-10): handling poll request
2020-07-31 13:35:49.899662 (Thread-10): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf46adcf8>]}
2020-07-31 13:35:49.903414 (Thread-10): sending response (<Response 2343 bytes [200 OK]>) to 10.0.7.111
2020-07-31 13:35:50.042077 (Thread-9): Found 2 models, 4 tests, 0 snapshots, 0 analyses, 136 macros, 0 operations, 0 seed files, 0 sources
2020-07-31 13:35:50.043097 (Thread-9): 
2020-07-31 13:35:50.043437 (Thread-9): Acquiring new snowflake connection "master".
2020-07-31 13:35:50.043571 (Thread-9): Opening a new connection, currently in state init
2020-07-31 13:35:50.046977 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "list_RAW".
2020-07-31 13:35:50.047080 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2020-07-31 13:35:50.061112 (ThreadPoolExecutor-0_0): Using snowflake connection "list_RAW".
2020-07-31 13:35:50.061205 (ThreadPoolExecutor-0_0): On list_RAW: /* {"app": "dbt", "dbt_version": "0.17.0", "profile_name": "user", "target_name": "default", "connection_name": "list_RAW"} */

    show terse schemas in database RAW
    limit 10000
2020-07-31 13:35:50.979044 (ThreadPoolExecutor-0_0): SQL status: SUCCESS 8 in 0.92 seconds
2020-07-31 13:35:50.984220 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:35:50.984324 (ThreadPoolExecutor-0_0): Re-using an available connection from the pool (formerly list_RAW).
2020-07-31 13:35:50.984512 (ThreadPoolExecutor-0_0): Creating schema "RAW.dbt_kcoapman"
2020-07-31 13:35:50.990209 (ThreadPoolExecutor-0_0): Using snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:35:50.990295 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: BEGIN
2020-07-31 13:35:51.060318 (Thread-11): handling poll request
2020-07-31 13:35:51.060762 (Thread-11): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf46cbcc0>]}
2020-07-31 13:35:51.063068 (Thread-11): sending response (<Response 5015 bytes [200 OK]>) to 10.0.31.94
2020-07-31 13:35:51.130099 (ThreadPoolExecutor-0_0): SQL status: SUCCESS 1 in 0.14 seconds
2020-07-31 13:35:51.130197 (ThreadPoolExecutor-0_0): Using snowflake connection "create_RAW_dbt_kcoapman".
2020-07-31 13:35:51.130255 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: /* {"app": "dbt", "dbt_version": "0.17.0", "profile_name": "user", "target_name": "default", "connection_name": "create_RAW_dbt_kcoapman"} */
create schema if not exists RAW.dbt_kcoapman
2020-07-31 13:35:51.592125 (ThreadPoolExecutor-0_0): Snowflake query id: 0195ef6f-03e7-9f8f-0007-9783002334e2
2020-07-31 13:35:51.592263 (ThreadPoolExecutor-0_0): Snowflake error: 003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'RAW'
2020-07-31 13:35:51.592344 (ThreadPoolExecutor-0_0): On create_RAW_dbt_kcoapman: ROLLBACK
2020-07-31 13:35:51.592397 (ThreadPoolExecutor-0_0): initiating rollback
2020-07-31 13:35:51.918415 (ThreadPoolExecutor-0_0): Error running SQL: macro create_schema
2020-07-31 13:35:51.918549 (ThreadPoolExecutor-0_0): Rolling back transaction.
2020-07-31 13:35:51.919512 (Thread-9): Connection 'master' was properly closed.
2020-07-31 13:35:51.919714 (Thread-9): Connection 'create_RAW_dbt_kcoapman' was left open.
2020-07-31 13:35:51.919779 (Thread-9): On create_RAW_dbt_kcoapman: Close
2020-07-31 13:35:52.169046 (Thread-9): dbt runtime exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 158, in exception_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 74, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/cursor.py", line 597, in execute
    errvalue)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.ProgrammingError: 003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'RAW'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dbt/rpc/task_handler.py", line 95, in task_exec
    result = self.task.handle_request()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/cli.py", line 110, in handle_request
    return self.real_task.handle_request()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/rpc/project_commands.py", line 54, in handle_request
    return self.run()
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 409, in run
    result = self.execute_with_hooks(selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 369, in execute_with_hooks
    self.before_run(adapter, selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/run.py", line 202, in before_run
    super().before_run(adapter, selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 355, in before_run
    self.create_schemas(adapter, selected_uids)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 509, in create_schemas
    create_future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/task/runnable.py", line 478, in create_schema
    adapter.create_schema(relation)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/impl.py", line 183, in create_schema
    self.execute_macro(CREATE_SCHEMA_MACRO_NAME, kwargs=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 976, in execute_macro
    result = macro_function(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 296, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 226, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 19, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 296, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 226, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 101, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 296, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 226, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 28, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 296, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/clients/jinja.py", line 226, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/usr/local/lib/python3.6/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/base/impl.py", line 228, in execute
    fetch=fetch
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 119, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 306, in add_query
    abridge_sql_log=abridge_sql_log
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/sql/connections.py", line 82, in add_query
    return connection, cursor
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/dbt/adapters/snowflake/connections.py", line 177, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  003001 (42501): SQL access control error:
  Insufficient privileges to operate on database 'RAW'
2020-07-31 13:35:52.242018 (Thread-12): handling poll request
2020-07-31 13:35:52.242472 (Thread-12): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf4a72ef0>]}
2020-07-31 13:35:52.243379 (Thread-12): sending response (<Response 18313 bytes [200 OK]>) to 10.0.7.55
2020-07-31 13:35:52.448281 (Thread-13): handling status request
2020-07-31 13:35:52.448737 (Thread-13): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf46c35c0>]}
2020-07-31 13:35:52.450104 (Thread-13): sending response (<Response 2486 bytes [200 OK]>) to 10.0.0.212
2020-07-31 13:38:25.365577 (Thread-14): handling status request
2020-07-31 13:38:25.366061 (Thread-14): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf46c3f98>]}
2020-07-31 13:38:25.367645 (Thread-14): sending response (<Response 2486 bytes [200 OK]>) to 10.0.34.28
2020-07-31 13:38:25.389340 (Thread-15): handling ps request
2020-07-31 13:38:25.389683 (Thread-15): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '13a3eded-3c91-49e7-a899-baa44b60ace1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2cf46cff60>]}
2020-07-31 13:38:25.391580 (Thread-15): sending response (<Response 500 bytes [200 OK]>) to 10.0.16.100
2020-08-04 12:14:43.446012 (MainThread): Running with dbt=0.17.0
2020-08-04 12:14:43.614309 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=False, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='default', models=None, partial_parse=True, port=8580, profile='user', profiles_dir='/usr/src/develop/.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2020-08-04 12:14:43.625292 (MainThread): Tracking: tracking
2020-08-04 12:14:43.625433 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e85208668>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e852084e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e85208518>]}
2020-08-04 12:14:43.625671 (MainThread): Serving RPC server at 0.0.0.0:8580, pid=13
2020-08-04 12:14:43.626657 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'get-manifest', 'kill', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2020-08-04 12:14:43.634821 (MainThread): Send requests to http://localhost:8580/jsonrpc
2020-08-04 12:14:43.638172 (Thread-1): Parsing macros/core.sql
2020-08-04 12:14:43.642625 (Thread-1): Parsing macros/materializations/helpers.sql
2020-08-04 12:14:43.650445 (Thread-1): Parsing macros/materializations/common/merge.sql
2020-08-04 12:14:43.673231 (Thread-1): Parsing macros/materializations/table/table.sql
2020-08-04 12:14:43.681178 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2020-08-04 12:14:43.686039 (Thread-1): Parsing macros/materializations/view/view.sql
2020-08-04 12:14:43.692177 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2020-08-04 12:14:43.719970 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2020-08-04 12:14:43.736334 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-08-04 12:14:43.738092 (Thread-1): Parsing macros/materializations/seed/seed.sql
2020-08-04 12:14:43.758601 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2020-08-04 12:14:43.764780 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2020-08-04 12:14:43.766714 (Thread-1): Parsing macros/etc/query.sql
2020-08-04 12:14:43.767791 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2020-08-04 12:14:43.769868 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2020-08-04 12:14:43.770867 (Thread-1): Parsing macros/etc/datetime.sql
2020-08-04 12:14:43.779680 (Thread-1): Parsing macros/etc/get_custom_database.sql
2020-08-04 12:14:43.781334 (Thread-1): Parsing macros/etc/is_incremental.sql
2020-08-04 12:14:43.783189 (Thread-1): Parsing macros/adapters/common.sql
2020-08-04 12:14:43.831766 (Thread-1): Parsing macros/schema_tests/relationships.sql
2020-08-04 12:14:43.832973 (Thread-1): Parsing macros/schema_tests/unique.sql
2020-08-04 12:14:43.834158 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2020-08-04 12:14:43.836131 (Thread-1): Parsing macros/schema_tests/not_null.sql
2020-08-04 12:14:43.837338 (Thread-1): Parsing macros/adapters.sql
2020-08-04 12:14:43.859163 (Thread-1): Parsing macros/catalog.sql
2020-08-04 12:14:43.861071 (Thread-1): Parsing macros/materializations/incremental.sql
2020-08-04 12:14:43.869974 (Thread-1): Parsing macros/materializations/merge.sql
2020-08-04 12:14:43.871967 (Thread-1): Parsing macros/materializations/table.sql
2020-08-04 12:14:43.875564 (Thread-1): Parsing macros/materializations/view.sql
2020-08-04 12:14:43.898551 (Thread-1): * Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - my_new_project

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0
2020-08-04 12:14:44.023659 (Thread-1): Acquiring new snowflake connection "model.my_new_project.my_second_dbt_model".
2020-08-04 12:14:44.023797 (Thread-1): Opening a new connection, currently in state init
2020-08-04 12:14:44.052614 (Thread-1): Acquiring new snowflake connection "model.my_new_project.my_first_dbt_model".
2020-08-04 12:14:44.052753 (Thread-1): Opening a new connection, currently in state init
2020-08-04 12:14:45.783651 (Thread-2): handling status request
2020-08-04 12:14:45.784158 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'aa4edb5b-829d-47ce-82fc-96a65e23532f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e880ddef0>]}
2020-08-04 12:14:45.788941 (Thread-2): sending response (<Response 9901 bytes [200 OK]>) to 10.0.7.105
2020-08-04 12:15:04.497256 (Thread-3): handling status request
2020-08-04 12:15:04.499043 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'aa4edb5b-829d-47ce-82fc-96a65e23532f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8e849bb128>]}
2020-08-04 12:15:04.502875 (Thread-3): sending response (<Response 9901 bytes [200 OK]>) to 10.0.42.218
